{{- if .Values.externalSecrets.enabled -}}
{{- range $externalSecret := .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name | quote }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with $externalSecret.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with $.Values.common.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $externalSecret.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval | default "1m" }}
  secretStoreRef:
    kind: {{ $externalSecret.secretStoreKind }}
    name: {{ $externalSecret.secretStoreName | default $.Release.Name }}
  target:
    name: {{ $externalSecret.targetSecretName }}
    creationPolicy: {{ $externalSecret.creationPolicy | default "Owner" }}
    {{- with $externalSecret.template }}
    template:
      engineVersion: v2
      data: {{ toYaml . | nindent 8 }}
    {{- end }}
  {{- if $externalSecret.data }}
  data:
  {{- range $externalSecret.data}}
    - secretKey: {{ .secretKey }}
      {{- with .remoteRef }}
      remoteRef:
        {{- toYaml . | nindent 8}}
      {{- end }}
  {{- end }}
  {{- end }}
  dataFrom:
  {{- with $externalSecret.extract }}
    {{- range . }}
    - extract:
        key: {{ . }}
        {{- with $externalSecret.decodingStrategy }}
        decodingStrategy: {{ toYaml . }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- with $externalSecret.findRegex }}
    - find:
        name:
          regexp: {{ . }}
        {{- with $externalSecret.decodingStrategy }}
        decodingStrategy: {{ toYaml . }}
        {{- end }}
      rewrite:
      - regexp:
          source: "{{ . }}(.*)"
          target: "$1"
  {{- end }}
  {{- with $externalSecret.extraDataFrom }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
