{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" . | quote }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.common.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.externalSecrets.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName | default .Release.Name }}
  target:
    name: {{ include "application.externalSecrets.targetSecretName" . }}
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  {{- with .Values.externalSecrets.variables }}
  data:
    {{- range . }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ . }}
    {{- end }}
  {{- end }}
  dataFrom:
  {{- with .Values.externalSecrets.extract }}
    {{- range . }}
    - extract:
        key: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.externalSecrets.findRegex }}
    - find:
        name: 
          regexp: {{ . }}
      rewrite:
      - regexp:
          source: "{{ . }}(.*)"
          target: "$1"
  {{- end }}
  {{- with .Values.externalSecrets.extraDataFrom }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}