{{- range .Values.application.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.name" $ }}{{- with .nameSuffix }}-{{- . }}{{- end }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with .labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with $.Values.common.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.application.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  template:
    metadata:
      annotations: 
        {{- with $.Values.common.annotations }}{{- toYaml . | nindent 8 }}{{- end }}
        {{- with $.Values.application.annotations }}{{- toYaml . | nindent 8 }}{{- end }}
        {{- with .annotations }}{{- toYaml . | nindent 8 }}{{- end }}
      labels:
        {{- include "application.labels" $ | nindent 8 }}
        {{- with .labels }}{{- toYaml . | nindent 8 }}{{- end }}
    spec:
      restartPolicy: {{ .restartPolicy }}
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" $ }}
      containers:
      - name: {{ $.Chart.Name }}
        image: {{ include "application.image" $ | quote }}
        command: {{- toYaml .command | nindent 10 }}
        {{- with .args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
        lifecycle: {{- toYaml .lifecycle | nindent 10 }}
        env:
          {{- range $key, $value := merge (default dict .env) $.Values.application.env $.Values.common.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- with $.Values.application.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $.Values.common.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        envFrom:
          {{- if $.Values.configmap.enabled }}
          - configMapRef:
              name: {{ default (include "application.name" $) $.Values.configmap.name }}{{- end }}
          {{- range $.Values.application.extraEnvConfigMaps }}
          - configMapRef:
              name: {{ . }}{{- end }}
          {{- range $.Values.common.extraEnvConfigMaps }}
          - configMapRef:
              name: {{ . }}{{- end }}
          {{- range .extraEnvSecrets }}
          - secretRef:
              name: {{ . }}{{- end }}
          {{- range $.Values.application.extraEnvSecrets }}
          - secretRef:
              name: {{ . }}{{- end }}
          {{- range $.Values.common.extraEnvSecrets }}
          - secretRef:
              name: {{ . }}{{- end }}
          {{- if $.Values.externalSecrets.enabled }}
          {{- range $.Values.externalSecrets.secrets }}
          {{- if .exposeToEnv }}
          - secretRef:
              name: {{ .targetSecretName | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
        {{- with $.Values.application.volumeMounts }}
        volumeMounts: {{- toYaml . | nindent 10 }}{{- end }}
        securityContext: {{- $.Values.application.containerSecurityContext | default $.Values.common.containerSecurityContext | toYaml | nindent 10 }}
      nodeSelector:      {{- $.Values.application.nodeSelector | default $.Values.common.nodeSelector | toYaml | nindent 8 }}
      tolerations:       {{- $.Values.application.tolerations | default $.Values.common.tolerations | toYaml | nindent 8 }}
      affinity:          {{- $.Values.application.affinity | default $.Values.common.affinity | toYaml | nindent 8 }}
      securityContext:   {{- $.Values.application.podSecurityContext | default $.Values.common.podSecurityContext | toYaml | nindent 8 }}
      priorityClassName: {{ $.Values.application.priorityClassName | default $.Values.common.priorityClassName | quote }}
      volumes:
        {{- with $.Values.application.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
        {{- with .volumes }}{{- toYaml . | nindent 8 }}{{- end }}
---
{{- end -}}
