{{- if .Values.application.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.application.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
{{- end }}