{{- range .Values.application.persistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with .labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with $.Values.common.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.application.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .annotations }}{{- toYaml . | nindent 4 }}{{- end }}
  name: {{ .name }}
spec:
  accessModes:
{{ toYaml .accessModes | indent 4 }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .storageClass }}"
{{- end }}
{{- end }}
{{- if .volumeBindingMode }}
  volumeBindingMode: "{{ .volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .size }}"
---
{{- end -}}
