{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.common.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.serviceAccount.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
{{- end }}
