{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "application.name" . | quote }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "application.name" . }}
  endpoints:
  - port: {{ .Values.service.name }}
    interval: {{ .Values.serviceMonitor.interval | quote }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.scheme }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml .Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    path: {{ .Values.serviceMonitor.path | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  jobLabel: {{ include "application.name" . | quote }}
{{- end }}